apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpark-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: smartpark-api

  template:
    metadata:
      labels:
        app: smartpark-api

    spec:
      serviceAccountName: smartpark-ksa

      volumes:
        - name: model-volume
          emptyDir: {}

        - name: image-volume
          emptyDir: {}

      initContainers:
        - name: download-assets
          image: google/cloud-sdk:slim

          command:
            - sh
            - -c
            - |
              set -e

              echo "Downloading YOLO model..."
              gcloud storage cp \
                gs://assignment1-smartpark-model-568039924052/model.pt \
                /models/model.pt

              echo "Downloading parking images..."
              mkdir -p /data/images

              gcloud storage cp --recursive \
                gs://assignment1-smartpark-model-568039924052/images/* \
                /data/images/

              echo "Model:"
              ls -lh /models/model.pt

              echo "Image count:"
              find /data/images -type f | wc -l

          volumeMounts:
            - name: model-volume
              mountPath: /models

            - name: image-volume
              mountPath: /data

      containers:
        - name: smartpark-api
          image: australia-southeast1-docker.pkg.dev/assignment1-smartpark/smartpark-repo/smartpark-api:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: YOLO_MODEL_PATH
              value: "/models/model.pt"

            - name: IMAGES_FOLDER
              value: "/data/images"

            - name: NUM_CARPARKS
              value: "10"

            - name: CACHE_TTL_SECS
              value: "10"

            - name: YOLO_CONFIG_DIR
              value: "/tmp/Ultralytics"

          volumeMounts:
            - name: model-volume
              mountPath: /models

            - name: image-volume
              mountPath: /data

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"

            limits:
              cpu: "2"
              memory: "4Gi"